# Generated by Django 5.0.1 on 2024-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['-id'],
            },
        ),
    ]
