# Generated by Django 4.1.13 on 2024-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
